### ISSUE TITLE
Download links have expired

### ISSUE THREAD

**Issue by guozixunnicolas** [chrisdonahue/nesmdb#16]
Many thanks for the detailed explanation of the dataset! 

Could you please provide the download links as they seem to have expired? 

Best,
Nicolas

**Comment by chrisdonahue** [comment]
Fixed! Apologies for the delay.

**Comment by chrisdonahue** [comment]
(see README for updated download links)

**Comment by guozixunnicolas** [comment]
Thanks so much!
